"""initial schema with food_id fk

Revision ID: f356930f4fe9
Revises: 
Create Date: 2026-06-23 10:11:22.162958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f356930f4fe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Text(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_date')
    )
    op.create_table('circumference_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Text(), nullable=False),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('arm_cm', sa.Float(), nullable=True),
    sa.Column('thigh_cm', sa.Float(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_date')
    )
    op.create_table('exercise_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('protein_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('fat_per_100g', sa.Float(), nullable=False),
    sa.Column('search_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=False),
    sa.Column('target_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activity_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keep_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('id = 1', name='profile_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diet_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_log_food_id'), ['food_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_log_food_id'))

    op.drop_table('diet_log')
    op.drop_table('profile')
    op.drop_table('food')
    op.drop_table('exercise_log')
    op.drop_table('circumference_log')
    op.drop_table('body_log')
    # ### end Alembic commands ###
